name: GitHub Actions Demo
run-name: ${{ github.actor }}
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I love prop scout"
      - run: echo "I love Sunday"
